npx vercel env add ALBY_ACCESS_TOKEN production --value "YTHMNZFMYTUTODI0ZS0ZNDE0LWI4ZWMTOGJHNWFHZWEZN2Q0" --force --yes
npx vercel env add ALBY_ACCESS_TOKEN preview --value "YTHMNZFMYTUTODI0ZS0ZNDE0LWI4ZWMTOGJHNWFHZWEZN2Q0" --force --yes
npx vercel env add ALBY_ACCESS_TOKEN development --value "YTHMNZFMYTUTODI0ZS0ZNDE0LWI4ZWMTOGJHNWFHZWEZN2Q0" --force --yes
npx vercel env add MDK_SECRET production --value "any_random_32_char_string_here_abcdef123456" --force --yes
npx vercel env add MDK_SECRET preview --value "any_random_32_char_string_here_abcdef123456" --force --yes
npx vercel env add MDK_SECRET development --value "any_random_32_char_string_here_abcdef123456" --force --yes
npx vercel env add MDK_WEBHOOK_SECRET production --value "another_random_32_char_secret_here" --force --yes
npx vercel env add MDK_WEBHOOK_SECRET preview --value "another_random_32_char_secret_here" --force --yes
npx vercel env add MDK_WEBHOOK_SECRET development --value "another_random_32_char_secret_here" --force --yes
npx vercel env add NEXT_PUBLIC_SUPABASE_URL production --value "https://cdfulrpfbboddcoawmpn.supabase.co" --force --yes
npx vercel env add NEXT_PUBLIC_SUPABASE_URL preview --value "https://cdfulrpfbboddcoawmpn.supabase.co" --force --yes
npx vercel env add NEXT_PUBLIC_SUPABASE_URL development --value "https://cdfulrpfbboddcoawmpn.supabase.co" --force --yes
npx vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production --value "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZnVscnBmYmJvZGRjb2F3bXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxMzgwOTgsImV4cCI6MjA5MjcxNDA5OH0.dUBkqElJyAj1Hkp21R5ktv0zzOZP5loOOTcMWQWA1wE" --force --yes
npx vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY preview --value "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZnVscnBmYmJvZGRjb2F3bXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxMzgwOTgsImV4cCI6MjA5MjcxNDA5OH0.dUBkqElJyAj1Hkp21R5ktv0zzOZP5loOOTcMWQWA1wE" --force --yes
npx vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY development --value "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZnVscnBmYmJvZGRjb2F3bXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxMzgwOTgsImV4cCI6MjA5MjcxNDA5OH0.dUBkqElJyAj1Hkp21R5ktv0zzOZP5loOOTcMWQWA1wE" --force --yes
npx vercel env add SUPABASE_SERVICE_ROLE_KEY production --value "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZnVscnBmYmJvZGRjb2F3bXBuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzEzODA5OCwiZXhwIjoyMDkyNzE0MDk4fQ.GZqSa9Vdi9Uuxi6XGAg70pTXh_2RdDtQLA4Q42Qgmt4" --force --yes
npx vercel env add SUPABASE_SERVICE_ROLE_KEY preview --value "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZnVscnBmYmJvZGRjb2F3bXBuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzEzODA5OCwiZXhwIjoyMDkyNzE0MDk4fQ.GZqSa9Vdi9Uuxi6XGAg70pTXh_2RdDtQLA4Q42Qgmt4" --force --yes
npx vercel env add SUPABASE_SERVICE_ROLE_KEY development --value "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZnVscnBmYmJvZGRjb2F3bXBuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzEzODA5OCwiZXhwIjoyMDkyNzE0MDk4fQ.GZqSa9Vdi9Uuxi6XGAg70pTXh_2RdDtQLA4Q42Qgmt4" --force --yes
npx vercel env add NEXT_PUBLIC_APP_URL production --value "https://rich-cars-clap.loca.lt" --force --yes
npx vercel env add NEXT_PUBLIC_APP_URL preview --value "https://rich-cars-clap.loca.lt" --force --yes
npx vercel env add NEXT_PUBLIC_APP_URL development --value "https://rich-cars-clap.loca.lt" --force --yes
npx vercel env add SUMMARIZE_SERVICE_ID production --value "afa42488-11de-4ff4-8ab3-8accba06f2fe" --force --yes
npx vercel env add SUMMARIZE_SERVICE_ID preview --value "afa42488-11de-4ff4-8ab3-8accba06f2fe" --force --yes
npx vercel env add SUMMARIZE_SERVICE_ID development --value "afa42488-11de-4ff4-8ab3-8accba06f2fe" --force --yes
npx vercel env add BTC_PRICE_SERVICE_ID production --value "7749f73a-4062-41f3-a765-a11457e5f096" --force --yes
npx vercel env add BTC_PRICE_SERVICE_ID preview --value "7749f73a-4062-41f3-a765-a11457e5f096" --force --yes
npx vercel env add BTC_PRICE_SERVICE_ID development --value "7749f73a-4062-41f3-a765-a11457e5f096" --force --yes
npx vercel env add CODE_REVIEW_SERVICE_ID production --value "a39b6ee0-db17-4333-b7be-a283fff16955" --force --yes
npx vercel env add CODE_REVIEW_SERVICE_ID preview --value "a39b6ee0-db17-4333-b7be-a283fff16955" --force --yes
npx vercel env add CODE_REVIEW_SERVICE_ID development --value "a39b6ee0-db17-4333-b7be-a283fff16955" --force --yes
npx vercel env add TRANSLATE_SERVICE_ID production --value "d6fe3e8d-58cf-433c-8468-593ecc710a76" --force --yes
npx vercel env add TRANSLATE_SERVICE_ID preview --value "d6fe3e8d-58cf-433c-8468-593ecc710a76" --force --yes
npx vercel env add TRANSLATE_SERVICE_ID development --value "d6fe3e8d-58cf-433c-8468-593ecc710a76" --force --yes
npx vercel env add VERIFY_WALLET_SERVICE_ID production --value "79ebb7a3-8cf5-4723-9c89-f2a4ed724e79" --force --yes
npx vercel env add VERIFY_WALLET_SERVICE_ID preview --value "79ebb7a3-8cf5-4723-9c89-f2a4ed724e79" --force --yes
npx vercel env add VERIFY_WALLET_SERVICE_ID development --value "79ebb7a3-8cf5-4723-9c89-f2a4ed724e79" --force --yes
